# Non Graded Challenge 6

- Name  : Cici Yuriza
- Batch : HCK-005

1. Membuktikan apakah vector ([1,3]) adalah eigen vector dari matrix [[1,-1],[6,4]]. Jika iya maka hitung eigen value-nya.

In [3]:
# import library
import numpy as np

In [38]:
# define matrix A
A = np.array([[1,-1],[6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [43]:
# define vector
vector = np.array([[1],[3]])
vector

array([[1],
       [3]])

In [44]:
# get values and vectors from matrix A 
values, vectors = np.linalg.eig(A)
values, vectors
print(f'values :\n',values)
print(f'vectors : \n',vectors)

values :
 [2.5+1.93649167j 2.5-1.93649167j]
vectors : 
 [[ 0.23145502-0.29880715j  0.23145502+0.29880715j]
 [-0.9258201 +0.j         -0.9258201 -0.j        ]]


In [46]:
2.5 * vector == A @ vector

array([[False],
       [False]])

In [47]:
-2.5 * vector == A @ vector

array([[False],
       [False]])