# Non Graded Challenge 5

- name   : Cici Yuriza
- batch : HCK-005

### Working Area

#### Import Library

In [2]:
# import library yang akan digunakan
import numpy as np
import matplotlib.pyplot as plt

#### 1. Make tensor 

In [24]:
# membuat array A, B, C, dan D masing-masing 2D
A = np.array([[23,50],[7,12]])
B = np.array([[57,67],[99,43]])
C = np.array([[75,21],[57,12]])
D = np.array([[87,26],[18,84]])

# membuat tensor 4 dimensi
tensor = np.array([[A],[B],[C],[D]])
tensor


array([[[[23, 50],
         [ 7, 12]]],


       [[[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]]],


       [[[87, 26],
         [18, 84]]]])

#### 2. Perkalian matrix A dan B

In [25]:
# membuat matrix 2D, dengan ukuran matrix 3x3
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
A

In [26]:
# membuat matrix 2D, dengan ukuran matrix 3x1
B = np.array([[17],[22],[19]])
B

In [30]:
# perkalian matrix A dan B
A * B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [29]:
# perkalian dot product matrix A dan B
A @ B

array([[1852],
       [2454],
       [4305]])

#### 3. Lakukan Transpose, hitung determinan dan inverse matrix

In [32]:
# membuat matrix 2D 3x3
A = np.array([[23, 50, 19],[7, 12, 109],[57, 67, 98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [49]:
# transpose matrix A
A = A.transpose()
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [50]:
# hitung determinan matrix A
determinan = np.linalg.det(A)
determinan

131344.0000000002

In [51]:
# invers matrix A
invers =np.linalg.inv(A)
invers

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])